openapi: 3.0.3

info:
  title: Price service
  version: 1.0.0
  description: The e-commerce price service

servers:
  - url: http://localhost:8080/api
    description: Local server

paths:
  /products/{idProduct}/brands/{idBrand}:
    get:
      summary: This endpoint queries certain data in the price table
      operationId: getProductData
      parameters:
        - name: idProduct
          in: path
          description: Product identifier
          required: true
          schema:
            type: integer
            default: 35455
        - name: idBrand
          in: path
          description: Brand identifier
          required: true
          schema:
            type: integer
            default: 1
        - name: applicationDate
          in: query
          description: Date application of the rate
          required: true
          schema:
            type: string
            default: 2020-06-14 00.00.00
      responses:
        200:
          description: Success!
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PriceResponseDTO'
        404:
          description: Not Found
          content:
            text/plain:
              schema:
                type: string
                example: Not Found
        400:
          description: Bad Request
          content:
            text/plain:
              schema:
                type: string
                example: Bad Request
        500:
          description: Internal server error
          content:
            text/plain:
              schema:
                type: string
                example: Internal Server Error
        default:
          description: Unexpected error
          content:
            text/plain:
              schema:
                type: string
                example: Unknow error

components:
  schemas:
    PriceRequestDto:
      description: This is the request price model
      type: object
      required:
        - productId
        - brandId
        - applicationDate
      properties:
        productId:
          description: This is the product identifier
          type: integer
          minimum: 1
        brandId:
          description: This is the brand identifier
          type: integer
          minimum: 1
        applicationDate:
          description: This is the application date
          type: string
          example: 2020-06-14 15.00.00
          minLength: 16
          maxLength: 19

    PriceResponseDTO:
      description: This is the response price model
      type: object
      properties:
        productId:
          description: This is the product identifier
          type: integer
          minimum: 1
        brandId:
          description: This is the brand identifier
          type: integer
          minimum: 1
        rate:
          description: This is the rate
          type: integer
          example: 3
          minimum: 1
        startDate:
          description: This is the rate starting date
          type: string
          example: 2020-06-14 15.00.00
          minLength: 16
          maxLength: 19
        endDate:
          description: This is the rate ending date
          type: string
          example: 2020-06-14 18.30.00
          minLength: 16
          maxLength: 19
        pvp:
          description: The final price
          type: number
          format: double
          example: 31.95